### PR TITLE
Drop warning about unloadNamespace

### PR DESCRIPTION
**Pull request by hadley**
Since (a) I think we do a lot better than we used to and (b) I've never noticed problems that required a restart.

### CODE REVIEW

**Review by lionel- — APPROVED** [review]
One remaining problem that I can think of is that we don't unregister lazily registered methods since they don't appear in the DESCRIPTION file. This could cause confusion when such a method is removed from the package during development but keeps being active. This should be rather rare though.

(I found this out using memtools because this is one of the ways a pkgloaded namespace can survive GC, the methods lazily registered in other namespaces keep references onto it)

**Comment by jimhester** [comment]
Documentation is also a problem and still can cause crashes.

**Comment by hadley** [comment]
I think my key problem with this message is that (a) it's too far away from the eventual problem so you're unlikely to remember the advice when you see the error and (b) it primarily affects us and we already know to restart.

**Comment by jimhester** [comment]
I mean I am fine removing the message and I agree I doubt people would connect this message to the problems, but problems do still exist.

**Pull request merged**
