### PR TITLE
Load package translations

### PR DESCRIPTION
**Pull request by hadley**

### CODE REVIEW

**Comment by hadley** [comment]
I've implemented a strategy where I just delete all previous temp dirs. I think this should be robust enough.

**Comment by hadley** [comment]
@gaborcsardi I think you commented just before I realised that myself 😆

**Comment by gaborcsardi** [comment]
> I've implemented a strategy where I just delete all previous temp dirs. I think this should be robust enough.

That's a good idea! But then I think it would be best to include the package name in the temp dir name, and only clean up the temp dirs of the package that is being loaded. Because multiple packages can be `load_all()`-d and they would remove each-others translations.

**Comment by MichaelChirico** [comment]
> The only mention of the "cache" in the manual is

FWIW there's also this mention:

https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Localization-of-messages

> Note that translated messages may be cached, so attempting to change the language of an error that has already been output in another language may not work.

I've never been able to pin down what exactly is implied by this note, but it looks like it's related to the issues Gabor cites.

**Comment by gaborcsardi** [comment]
@MichaelChirico Some versions of gettext do this, apparently. We have seen it with brew R, and the gettext it links to on macOS. We haven't seen it with R's internal gettext so far.

**Review by gaborcsardi — APPROVED** [review]

**Comment by hadley** [comment]
I wonder if this is the same root cause: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931456

**Pull request merged**
