### PR TITLE
Unload S3 methods instead of forcing package bindings

### PR DESCRIPTION
**Pull request by lionel-**
Follow-up to r-lib/devtools#1001 which forces all bindings of a namespace prior to reloading, to avoid lazy-load errors with registered S3 methods. Instead of forcing bindings, we remove the S3 methods from the relevant S3 tables before reloading a package.

- This improves the loading behaviour with packages that define objects in their namespaces lazily (e.g. with `delayedAssign()`).

- This also makes `load_all()` more predictable after a method has been removed from the package. It is now actually removed from the generic table. It would previously linger until R was restarted.

### CODE REVIEW

**Comment by lionel-** [comment]
The 3.4 failure is unrelated

```
Error: Package required but not available: ‘rstudioapi’
```

**Comment by jimhester** [comment]
Thank you!

**Comment by gaborcsardi** [comment]
@lionel- @jimhester Why not do this in `unload()` instead of `load_all()`? Then the package can also be re-loaded with `library()`?

**Comment by jimhester** [comment]
Yeah, we can do that

**Comment by lionel-** [comment]
That makes sense. I'll send another PR unless you're already working on this @jimhester

**Comment by jimhester** [comment]
Sure another PR would be welcome, thanks @lionel-!

**Pull request merged**
