### PR TITLE
Option to turn off helper loading

### PR DESCRIPTION
**Pull request by pitakakariki**
This was originally a pull request for devtools: https://github.com/hadley/devtools/pull/1169

### CODE REVIEW

**Comment by pitakakariki** [comment]
I think the failed checks are something to do with "testDllRcpp" rather than this pull request.

**Comment by hadley** [comment]
Thanks - just fixed that issue. Could you please merge changes from master?

**Comment by kforner** [comment]
great

**Comment by jimhester** [comment]
Thanks!

**Pull request merged**
